### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by marcpley** [marcpley/potaleger#6]
New issue from 
https://github.com/marcpley/potaleger/issues/1#issuecomment-2583482325

Libs listed with ldd are copied in `libs_potaleger` with the release compiled file `potaleger`:
![image](https://github.com/user-attachments/assets/9bd1db72-baab-4b39-b438-30968bdbf245)

`potaleger.sh` is used to set `LD_LIBRARY_PATH` and launch the app :
```
#!/bin/bash
DIR=$(dirname "$0")
export LD_LIBRARY_PATH="$DIR/libs_potaleger"
"$DIR/libs/potaleger" "$@"
```
When trying to run on another linux mint system without Qt installed I have this error:
```
lammens@bim-Aspire-5733:~/Bureau/Potaléger$ ./potaleger.sh 
./libs_potaleger/potaleger: symbol lookup error: ./libs_potaleger/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
```
If I remove `libc.so.6` of `libs_potaleger` dir I have:
```
lammens@bim-Aspire-5733:~/Bureau/Potaléger$ ./potaleger.sh 
./libs_potaleger/potaleger: symbol lookup error: ./libs_potaleger/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
lammens@bim-Aspire-5733:~/Bureau/Potaléger$ ./potaleger.sh 
./libs_potaleger/potaleger: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./libs_potaleger/potaleger)
./libs_potaleger/potaleger: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./libs_potaleger/potaleger)
./libs_potaleger/potaleger: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./libs_potaleger/libstdc++.so.6)
...
```

**Comment by pawelsalawa** [comment]
The problem here is you are compiling the app on relatively fresh Linux and trying to run it on a bit older. It's a common issue with Linux binaries. Usually the best solution is just to compile it on older Linux - that's why SQLiteStudio is compiled on the oldest Linux available in GitHub Actions.

**Comment by marcpley** [comment]
Compiling and deploying to Linux, Mac and Windows with GitHub actions would be great. It seem complex seeing your xxx_release.yml files !
What option do you recommend?
- Use GitHub to compile and deploy
- Using another computer with old Linux and old windows systems + Qt installed on both system
- Using docker on my dev computer (latest system) to compile for old systems.
- other ?

**Comment by pawelsalawa** [comment]
GitHub actions is most rubust way I think. I personally used to do it manually on my local virtual machines, but there were often some kind of issues that my local Linux machines had some dependency incompatible with many users around the world...

Using GitHub actions seem to provide widely compatible binaries. It requires much work initially, but then it's easy to reuse.

See this workflow - it should look simpler to start with: https://github.com/pawelsalawa/sqlite3-sqls/blob/main/.github/workflows/build_linux_x64.yml

Do it in iterations - first make your first workflow file to just compile your project. When that is successful you can move on to building a package as further steps of the workflow.

If you've never created GH actions, just create `github/workflows/` directory in root of your repository, then add workflow `*.yml` file and push that file to GitHub. The action will appear on Actions tab of your GH page.

**Comment by marcpley** [comment]
Let's do that :-)

I've create `.github/workflows/` directory in root of my repository on my local computer.
I copy in your yml file, and changed this line:
`https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/runs/${{ inputs.PARENT_RUN_ID }}/artifacts \`
to
`https://api.github.com/repos/marcpley/potaleger/actions/runs/${{ inputs.PARENT_RUN_ID }}/artifacts \`
May I keep all the file or it is just an example ?
After git push I see the Action on GH.
I don't understand the inputs (and the main part of the file)

**Comment by marcpley** [comment]
Let's do that :-)

I've create `.github/workflows/` directory in root of my repository on my local computer.
I copy in your yml file, and changed this line:
`https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/runs/${{ inputs.PARENT_RUN_ID }}/artifacts \`
to
`https://api.github.com/repos/marcpley/potaleger/actions/runs/${{ inputs.PARENT_RUN_ID }}/artifacts \`
May I keep all the file or it is just an example ?
After git push I see the Action on GH.
I don't understand the inputs (and the main part of the file)

**Comment by pawelsalawa** [comment]
You need to change the file significantly. It's just an example.

1. Remove inputs, but you need to keep the header of it, so:
```
on:
    workflow_dispatch:
        inputs:
          INT_VER:
            description: 'SQLite version as integer'
            required: true
            type: number
          PARENT_RUN_ID:
            description: 'ID of workflow that created appropriate amalgamation artifact'
            required: true
            type: number
```
should become:
```
on:
    workflow_dispatch:
        inputs:
```

2. Clean environment variables. You will add them as needed when necessary. For now these are irrelevant for you:
```
env:
    output_basename: sqlite3-linux-x64
    compilation_options: |
                    -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT \
                    -DSQLITE_ENABLE_DBSTAT_VTAB \
                    -DSQLITE_ENABLE_BYTECODE_VTAB \
                    -DSQLITE_ENABLE_COLUMN_METADATA \
                    -DSQLITE_ENABLE_EXPLAIN_COMMENTS \
                    -DSQLITE_ENABLE_FTS3 \
                    -DSQLITE_ENABLE_FTS4 \
                    -DSQLITE_ENABLE_FTS5 \
                    -DSQLITE_ENABLE_GEOPOLY \
                    -DSQLITE_ENABLE_JSON1 \
                    -DSQLITE_ENABLE_RTREE \
                    -DSQLITE_ENABLE_MATH_FUNCTIONS
```
should become:
```
env:
```

3. In 'steps:'  add step to install Qt before you compile anything:
```
            - name: Qt installation dir
              id: qt-installation-dir
              run: echo "DIR=$(readlink -f ${{ github.workspace }}/..)" >> $GITHUB_OUTPUT

            - name: Install Qt
              uses: jurplel/install-qt-action@v4
              with:
                cache: true
                version: 6.8.1
                host: 'linux'
                dir: '${{ steps.qt-installation-dir.DIR }}'
                setup-python: 'false'
                extra: '--external 7z'
```

4. Then checkout source codo of your project
```
            - name: Clone repo
              uses: actions/checkout@v3
              with:
                ref: main
```

5. Then you need to change completely this step:
```
             - name: Download Amalgamation
              shell: bash
              run: |
                set -x
                URL=$(
                    curl -s -L \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/runs/${{ inputs.PARENT_RUN_ID }}/artifacts \
                        | jq -r '.artifacts[0].archive_download_url'
                    )
                    
                ZIP_NAME=sqlite3-amalgamation-${{ inputs.INT_VER }}.zip
                echo "Downloading $ZIP_NAME from $URL"
                curl -s -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o $ZIP_NAME $URL
                ls -l
                
                unzip $ZIP_NAME
                ls -l

                gcc sqlite3.c -lpthread -ldl -lm -Os -fpic -shared -o libsqlite3.so ${{ env.compilation_options }}
                gcc shell.c sqlite3.c -lpthread -ldl -lm -Os -fpic -o sqlite3 ${{ env.compilation_options }}
                ls -l

                strip libsqlite3.so
                strip sqlite3
                ls -l
                
                OUTPUT_DIR=${{ env.output_basename }}-${{ inputs.INT_VER }}
                echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV
                mkdir $OUTPUT_DIR
                cp libsqlite3.so sqlite3 sqlite3.h sqlite3ext.h $OUTPUT_DIR/
```
After the `run: |` there is a bash script to build your project. You need to write it accordingly for your project. Here would go `qmake` call, then `make` and then copying all files into a directory, which becomes a package to upload (in last action step).

**Comment by marcpley** [comment]
I fail on step 5 :-(
In Projets -> Build steps
Effective qmake call:
`/home/marc/Qt/6.8.1/gcc_64/bin/qmake /home/marc/Documents/Projets/greli.net/potaleger/potaleger.pro -spec linux-g++ CONFIG+=qml_debug "QT += svg" && /bin/make qmake_all`
Make:
`make -j8 in /home/marc/Documents/Projets/greli.net/potaleger/build/Desktop_Qt_6_8_1-Debug`
Target directory:
`/home/marc/Bureau/greli.net/potaleger/zNoRepo/install`
Could you help for the bash script ?

I also install Qt on a Linux Mint 20.3 xfce system.
I compile SQLite on it (libsqlite3.a).
When I try to compile my projet, I have this error:
`undefined reference to symbol ‘dlclose@@GLIBC_2.2.5`

**Comment by pawelsalawa** [comment]
I think step 4 for you will be something like:
```
             - name: Compile
              shell: bash
              run: |
                mkdir install
                cd install
                qmake ../potaleger.pro "QT += svg"
                make -j 4
                ls -l
```

It's not final. It's about 30% complete, but let's see how that works. In the end it does `ls -l` so we can go to the action executed and if it's successful, you will see what files were produced. From that point it will be easier to decide how to build the zip package.

> I also install Qt on a Linux Mint 20.3 xfce system.

So Mint 20.3 is older or same as yours?

**Comment by marcpley** [comment]
Older. My dev system is Mint 22 cinamon.

**Comment by marcpley** [comment]
I done some tests with
https://docs.github.com/en/actions/writing-workflows/quickstart
I can now modify and run the workflow.
It fail on the Qt installation:
```
...
INFO    : Finished installation of icu-linux-Rhel8.6-x86_64.7z in 2.77367796
INFO    : Finished installation of qtdeclarative-Linux-RHEL_8_10-GCC-Linux-RHEL_8_10-X86_64.7z in 14.51849175
ERROR   : Updater caused an IO error: [Errno 2] No such file or directory: '/home/runner/work/potaleger/Qt/6.8.1/gcc_64/mkspecs/qconfig.pri'
Error: Error: The process '/usr/bin/python3' failed with exit code 1
```
The file `qconfig.pri` is present on my local system:
```
QT_ARCH = x86_64
QT_BUILDABI = x86_64-little_endian-lp64
QT_LIBCPP_ABI_TAG = 
QT.global.enabled_features = version_tagging shared pkg-config separate_debug_info rpath reduce_relocations signaling_nan zstd thread future concurrent dbus opensslv30 shared intelcet glibc_fortify_source stack_protector stack_clash_protection libstdcpp_assertions relro_now_linker shared separate_debug_info rpath reduce_exports reduce_relocations openssl
QT.global.disabled_features = static cross_compile debug_and_release appstore-compliant simulator_and_device force_asserts framework c++20 c++2a c++2b wasm-simd128 wasm-exceptions openssl-linked opensslv11
QT.global.disabled_features += release build_all
QT_CONFIG += shared separate_debug_info rpath reduce_exports reduce_relocations openssl release
CONFIG +=  shared plugin_manifest intelcet glibc_fortify_source stack_protector stack_clash_protection libstdcpp_assertions relro_now_linker
QT_VERSION = 6.8.1
QT_MAJOR_VERSION = 6
QT_MINOR_VERSION = 8
QT_PATCH_VERSION = 1

QT_GCC_MAJOR_VERSION = 10
QT_GCC_MINOR_VERSION = 3
QT_GCC_PATCH_VERSION = 1
```
Do I have to push this file somewhere ? How?

**Comment by pawelsalawa** [comment]
No, you don't have to add such files.

Let's remove this part and see if it helps:
```
                setup-python: 'false'
                extra: '--external 7z'
```

**Comment by marcpley** [comment]
Ok, Qt install passed.
Now the problem is here:
```
      - name: Clone repo
          uses: actions/checkout@v4.2.2
          with:
            repository: main
```
Error:
`You have an error in your yaml syntax on line 22`
It's the same with checkout@v3
The syntax seem good to me.

**Comment by pawelsalawa** [comment]
It should be:
```
      - name: Clone repo
          uses: actions/checkout@v4
          with:
            ref: main
```

**Comment by marcpley** [comment]
![image](https://github.com/user-attachments/assets/4b3ab459-edb5-4442-81f0-d48eea4b5238)

**Comment by pawelsalawa** [comment]
I see that you're actively working on the workflow and you reached the `qmake` step. For the `*.pro` file not found error, just add `ls -l` and `ls -l ..` before running qmake to find out what you have.

**Comment by marcpley** [comment]
qmake ok now.

make don't work:
```
...
 g++ -Wl,-O1 -Wl,-rpath,/home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib -Wl,-rpath-link,/home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib -o potaleger  Dialogs.o PotaUtils.o FunctionsSQLite.o Structure.o Data.o main.o mainwindow.o potawidget.o eval.o manage.o module.o qrc_images.o moc_mainwindow.o moc_potawidget.o   /home/runner/work/potaleger/potaleger/libs/sqlite/libsqlite3.a /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Svg.so -pthread /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Widgets.so /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Gui.so /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Sql.so /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Core.so -lpthread -lGL   
/usr/bin/ld: /home/runner/work/potaleger/potaleger/libs/sqlite/libsqlite3.a(sqlite3.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:300: potaleger] Error 1
Error: Process completed with exit code 2.
```
Do you have access to the workflow annotations ?

**Comment by marcpley** [comment]
There is no MakeFile file in my projet dir. Do I have to create one ?

**Comment by pawelsalawa** [comment]
No. Makefile is generated by `qmake`.

The problem here is again this GLIBC, because `libsqlite3.a` is compiled with incompatible libc version. If you link your SQLite statically anyway, then I would recommend you to just include `sqlite3.c` file into your project (just like you did with `define.c` etc). You can get `sqlite3.c` from https://sqlite.org/download.html - pick the "amalgamation" package, where you will find this file.

`sqlite3.c` is a single-file SQLite. It will get compiled together with your project on the same machine, which should solve your problem.

**Comment by marcpley** [comment]
`libsqlite3.a` removed off the project  (by modifying the .pro file) and `sqlite3.c` added (add file to projet).
Do I need to add the `sqlite3.h` too ? 
The err message is a bit different but the problem persists
```
g++ -Wl,-O1 -Wl,-rpath,/home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib -Wl,-rpath-link,/home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib -o potaleger  Dialogs.o PotaUtils.o FunctionsSQLite.o Structure.o Data.o main.o mainwindow.o potawidget.o eval.o manage.o module.o sqlite3.o qrc_images.o moc_mainwindow.o moc_potawidget.o   /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Svg.so -pthread /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Widgets.so /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Gui.so /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Sql.so /home/runner/work/potaleger/Qt/6.8.1/gcc_64/lib/libQt6Core.so -lpthread -lGL   
/usr/bin/ld: sqlite3.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:303: potaleger] Error 1
Error: Process completed with exit code 2.
```

**Comment by marcpley** [comment]
It looks like a local compiled file was pushed on github and used like this by workflow without being recompiled.

**Comment by pawelsalawa** [comment]
Yes, that looks like that was the case.

**Comment by marcpley** [comment]
The workflow completes if `runs-on: ubuntu-latest`
So the SQLite I use (3.48.0) need ubuntu-latest ?
I tried with 3.47.2 and it's the same.
Do you know how to get an older version of SQLite ? I don't found that on SQLite website.

**Comment by marcpley** [comment]
I've found how to get old SQLite versions.
With older SQLite version than 3.47.2, SQLean don't work (app crash). Even with an older version of SQLean (0.21.8 2023-08)
I tried SQLite 3.41.1 (2023-03-10), older than ubuntu 20.04.6 (2023-03-16), without SQLean: compile ok on my local system but still sqlite3.so problem on github workflow compile.

So I deduce that SQLite 3.47.2 or SQLean can't compile on ubuntu 20.04. Does that seem possible for you ?

**Comment by marcpley** [comment]
I set the runs-on to `ubuntu-22.04` and it compile with SQLite 3.48.0 (latest) and latest SQLean. **So I will use that**.
Now the compile step is ok.
How to retrieve the compiled file in the repository ?

I also manualy set a bundle of needed libs on my local system:
![image](https://github.com/user-attachments/assets/c3a7899c-20ce-46cd-9e4e-44b76a863cdd)
`ldd` just give the libs but not the plugins part.

How to set an `ubuntu-22.04` bundle ? Does workflow can do that ?

**Comment by pawelsalawa** [comment]
### Compiling different SQLite versions on different Ubuntus
SQLite should compile just fine on older Ubuntus available on GitHub just fine. I would recommend to use older (than latest) Ubuntu, to make the binary as compatible with older Linuxes as possible.

If your build fails on older Ubuntu, point me out to the failing workflow run which uses it and I will try to find out why it's happening.

SQLean also should compile with any recent (like not older than a year or so) SQLite. There are not big API changes in each SQLite version that would cause them to fail to compile.

...or if you're fine with SQLite 3.48.0 as you have now, you can just move on with this.

### Building the bundle
In SQLiteStudio I just have a step which copies all the files into the target directory of the bundle. I see no other way around it. In SQLiteStudio this is a complex task, because it uses many more dependencies: https://github.com/pawelsalawa/sqlitestudio/blob/3.4/.github/workflows/lin_release.yml

You can see there a lot of steps named like `Copy XYZ to portable dir` and `Fix dependency paths` - all of this is done to have the package deployable to other Linux machines.

In your case it will most likely be shorter, because you have less dependencies, but you can copy-paste parts about Qt (plus SQL Qt plugins, which SQLiteStudio does not use).

I think you can skip Qt dependencies about Networking and PrintSupport, as well as crypto and SSL (I use them for checking updates online and for PDF printing from SQLiteStudio).

### Getting your compiled files from the action
To make your compiled files available from your actions, just put at the and of action this step:
```
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: <here put a name under which the artifact will be published>
                path: <here put a file or directory path, which will be zipped by the action and it will become the published artifact>
```
After this step is done, you will have your artifact available at the bottom of the workflow run summary, like here:
https://github.com/pawelsalawa/sqlite3-sqls/actions/runs/12768067444

**Comment by marcpley** [comment]
> If your build fails on older Ubuntu, point me out to the failing workflow run which uses it and I will try to find out why it's happening.

https://github.com/marcpley/potaleger/actions/runs/12851467683/job/35832227583

I couldn't find a working combinaison older than SQLite 3.47.2 / SQLean latest. With older SQLite, my app crash on
`q1.exec("SELECT * FROM RF_trop_proches('xxx')")`
`RF_trop_proches` is a table valued function.
The scalar functions are ok.

**Comment by pawelsalawa** [comment]
For the 'dlclose' error, I believe it should be resolved if you add `LIBS += -ldl` to your *.pro file. I don't know why this is an issue when using one SQLite version and not for others. I have no idea.

**Comment by marcpley** [comment]
It works ! Workflow compile with ubuntu 20.4 and the app run on Mint 20 :-)
Thanks a lot.

What is ldl ? I didn't find clear information on it.

The next step is to create an installation app like the one you use for SQLStudio. What do you recommend?

**Comment by pawelsalawa** [comment]
Awesome!

> What is ldl ? I didn't find clear information on it.

https://stackoverflow.com/questions/19146525/meaning-of-library-dl-in-gcc

> The next step is to create an installation app like the one you use for SQLStudio. What do you recommend?

SQLiteStudio uses InstallBuilder, but it's paid solution and SQLiteStudio received free license as open source software. They have a FAQ entry for that: https://installbuilder.com/faq/i-have-an-open-source-project-can-i-use-installbuilder-for-free

Qt also has its own installer framework that you can use https://doc.qt.io/qtinstallerframework/

You can also just distribute zip packages.

**Comment by marcpley** [comment]
Potaléger is now  compiled for Linux, Windows and Mac.

**Comment by pawelsalawa** [comment]
Cool, congrats!
